language: python
python:
  - '3.6'
  - 'nightly'

cache: pip

services:
  - postgresql

install: 'pip install pytest-coverage codecov -r requirements.txt'

script: pytest --cov .

after_success: codecov
